[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.1.2" }
risc0-build-ethereum = {version = "1.1.4"}
[package.metadata.risc0]
methods = ["guest"]
