# syntax=docker/dockerfile:1

FROM zpokendev/zk-lite-client_gnark-wrapper_keys:latest as gnark_keys
FROM golang:1.22-alpine

# Install curl
RUN apk update && apk add --no-cache curl

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download
COPY --from=gnark_keys /app/api-build/ ./api-build/
COPY . ./

EXPOSE 8010

# Run
ENV USE_BIT_DECOMPOSITION_RANGE_CHECK=true
CMD ["go", "test", "-race", "-vet=off", "./..."]
