name: Crypto

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

env:
  RUST_VERSION_NIGHTLY: nightly-2023-10-24
  CARGO_TERM_COLOR: always

jobs:
  lint-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ env.RUST_VERSION_NIGHTLY }}
          components: clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

  lint-generic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install other dependencies
        run: sudo apt-get install moreutils dos2unix

      - name: Check encoding
        run: |
          find . -name '*.rs' -exec isutf8 {} +

      - name: Check line endings
        run: bash .github/workflows/scripts/check_line_endings.sh
