name: Gnark

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Verify dependencies
        working-directory: ./gnark-plonky2-verifier
        run: go mod verify

      - name: Build
        working-directory: ./gnark-plonky2-verifier
        run: go build -v ./...

  check:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install staticcheck
        working-directory: ./gnark-plonky2-verifier
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ./gnark-plonky2-verifier
        run: staticcheck ./...

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install golint
        working-directory: ./gnark-plonky2-verifier
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        working-directory: ./gnark-plonky2-verifier
        run: golint ./...